# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='SportMeet',
        ),
    ]
