# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200504_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmeet',
            name='numberofsm',
            field=models.IntegerField(default=0, verbose_name='参加此项目的人数'),
        ),
    ]
