# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_sportmeet_numberofsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmeet',
            name='smgroup',
            field=models.CharField(default=0, max_length=30, verbose_name='项目所属分组'),
        ),
        migrations.AlterField(
            model_name='sportmeet',
            name='description',
            field=models.CharField(max_length=100, verbose_name='项目简单描述'),
        ),
        migrations.AlterField(
            model_name='sportmeet',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='项目名称'),
        ),
    ]
