# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200504_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='公告标题')),
                ('description', models.CharField(max_length=100, verbose_name='公告类型')),
                ('numbers_of_sport_meet', models.CharField(default=0, max_length=150, verbose_name='公告内容')),
                ('sport_meet_group', models.CharField(default=0, max_length=30, verbose_name='上传部门')),
            ],
        ),
        migrations.RenameField(
            model_name='sportmeet',
            old_name='numberofsm',
            new_name='numbers_of_sport_meet',
        ),
        migrations.RenameField(
            model_name='sportmeet',
            old_name='smgroup',
            new_name='sport_meet_group',
        ),
    ]
