# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200504_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_grade', models.CharField(max_length=32, null=True, verbose_name='年级')),
                ('classes_class', models.CharField(max_length=64, null=True, verbose_name='班级')),
            ],
        ),
        migrations.AlterField(
            model_name='sportmeet',
            name='description',
            field=models.CharField(max_length=100, verbose_name='项目描述'),
        ),
    ]
