# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200504_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_nick', models.CharField(max_length=32, unique=True, verbose_name='用户名（昵称）')),
                ('user_pwd', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('user_phonenumber', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('user_role', models.CharField(blank=True, choices=[('manager', '管理员'), ('user', '用户')], default='manager', max_length=16, null=True, verbose_name='身份')),
                ('user_sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=32, null=True, verbose_name='性别')),
                ('user_academy', models.CharField(choices=[('school', '清华大学'), ('Mines', '矿业学院'), ('Law', '法学院'), ('Art_Design', '美术学院'), ('Economics', '经济学院'), ('Management', '管理学院'), ('Computer_Science', '计算机科学学院')], max_length=32, null=True, verbose_name='学院')),
            ],
        ),
    ]
