# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_suser'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='classes_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.Classes', verbose_name='班级'),
        ),
    ]
