# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_suser_classes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(choices=[('unapprove', '未通过'), ('approve', '通过'), ('unreview', '未审核')], default='unreview', max_length=20, null=True, verbose_name='审核状态')),
                ('sport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.SportMeet', verbose_name='运动项目')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.SUser', verbose_name='用户')),
            ],
        ),
    ]
