# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_item', models.CharField(max_length=64, verbose_name='公告标题')),
                ('notice_type', models.CharField(choices=[('picture_news', '图片新闻'), ('video_news', '视频新闻')], max_length=32, verbose_name='新闻类型')),
                ('notice_picture_content', models.ImageField(upload_to='p_content', verbose_name='图片新闻公告内容')),
                ('notice_video_content', models.FileField(upload_to='v_content', verbose_name='视频新闻公告内容')),
                ('notice_academy', models.CharField(choices=[('school', '清华大学'), ('Mines', '矿业学院'), ('Law', '法学院'), ('Art_Design', '美术学院'), ('Economics', '经济学院'), ('Management', '管理学院'), ('Computer_Science', '计算机科学学院')], max_length=32, null=True, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.SportMeet', verbose_name='运动项目')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.SUser', verbose_name='用户')),
            ],
        ),
    ]
