# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-04 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_notice_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_picture_content',
            field=models.ImageField(default=0, upload_to='p_content', verbose_name='图片新闻公告内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_video_content',
            field=models.FileField(default=0, upload_to='v_content', verbose_name='视频新闻公告内容'),
        ),
        migrations.AlterField(
            model_name='suser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('manager', '管理员'), ('user', '运动员')], default='manager', max_length=16, null=True, verbose_name='身份'),
        ),
    ]
